language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-component-app' ]; then cd .. && eval "mv $currentfolder generator-component-app" && cd generator-component-app; fi
